require:
  - rubocop-rspec
  - rubocop-performance

RSpec/MessageChain:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Max: 7

RSpec/ExampleLength:
  Max: 15

RSpec/MessageSpies:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'Gemfile'
    - 'spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/'
    - '*.gemspec'
  TargetRubyVersion: 2.5.5
